version: '3.1'
services:

  db:
    image: postgres
    restart: always
    hostname: db
    environment: 
      POSTGRES_USER: rafael
      POSTGRES_PASSWORD: admin

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080